config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/pages', to: 'pages#home'
  resources :resumes
  get '/product/index', to: 'pages#home'
  get 'dashboard/', to: 'dashboard#index'
  resources :articles, path: '/dashboard/articles'
  resources :categories, path: '/dashboard/categories'
  resources :products

  resources :staffs, path: '/dashboard/staffs'
  resources :users, :controllers => { :registrations => "registrations" }
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Slug
  field :title, type: String
  field :content, type: String
  slug :title, type: String
  belongs_to :category
end

app/models/category.rb
class Category
  include Mongoid::Document
  field :name, type: String
  has_many :articles
end

app/models/dashboard.rb
class Dashboard
  include Mongoid::Document
end

app/models/product.rb
class Product
  include Mongoid::Document
end

app/models/resume.rb
class Resume
  include Mongoid::Document
  field :name, type: String
  field :attachment, type: String
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :name,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  field :role, type: String, default: 'user'

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  layout 'dashboard'
  
  def index
    @articles = Article.all
    @categorys = Category.all
    @count = Article.count
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
    @categories = Category.all
  end
 
  def edit
    @article = Article.find(params[:id])
    @categories = Category.all
  end
 
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end
 
  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :content, :category_id, :name)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout "dashboard"
  def index
    @categories = Category.all
    @count = Category.count
    @articles = Article.all
  end
 
  def show
    @category = Category.find(params[:id])
    @articles = @category.articles
  end
 
  def new
    @category = Category.new
  end
 
  def edit
    @category = Category.find(params[:id])
  end
 
  def create
    @category = Category.new(category_params)
 
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end
 
  def update
    @category = Category.find(params[:id])
 
    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end
 
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
 
    redirect_to categories_path
  end
 
  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @pages = Article.all
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Article.all
  end
  def show
    @product = Article.find(params[:id])
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
      @resumes = Resume.all
   end
   
   def new
      @resume = Resume.new
   end
   
   def create
      @resume = Resume.new(resume_params)
      
      if @resume.save
         redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded."
      else
         render "new"
      end
      
   end
   
   def destroy
      @resume = Resume.find(params[:id])
      @resume.destroy
      redirect_to resumes_path, notice:  "The resume #{@resume.name} has been deleted."
   end
   
   private
      def resume_params
      params.require(:resume).permit(:name, :attachment)
   end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
   layout 'dashboard'
  
  def index
    @staffers = User.all
    @count = User.count
  end
 
  def show
    @staffs = User.find(params[:id])
  end
 
  def new
    @staffs = User.new
  end
 
  def edit
    @staffs = User.find(params[:id])
  end
 
  def create
    @staffs = User.new(staffs_params)
    if @staffs.save
      redirect_to staffs_path
    else
      render 'new'
    end
  end
 
  def update
    @staffs = User.find(params[:id])
 
    if @staffs.update(staffs_params)
      redirect_to @staffs
    else
      render 'edit'
    end
  end
 
  def destroy
    @staffs = User.find(params[:id])
    @staffs.destroy
 
    redirect_to staffs_path
  end
 
  private
    def staffs_params
      params.require(:user).permit(:email, :role)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  binding.pry
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<section>
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="col-lg-10"><h3 class="panel-title">Danh sách thể loại <span><%= @count %></span></h3> </div> <div class="col-lg-2"><%= link_to 'Thêm Thể loại', new_category_path %></div>
    </div>
    <div class="panel-body">
      <table class="table">
        
          <tr>
            <th>Tên thể loại</th>
            <th>Chức năng</th>
          </tr>  
        <% @categories.each do |c| %>
          </tr>  
          <td><%= c.name %></td>
          <td>
            <%= link_to 'Show', category_path(c) %>
            <%= link_to 'Edit', edit_category_path(c) %>
            <%= link_to 'Destroy', c, method: :delete, data: { confirm: 'Are you sure?' } %>
         </td>
        <% end %>
      </table>

  </div>
</section>

app/views/categories/new.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">New Sản Phẩm</h3>
  </div>
  <div class="panel-body">
    <%= form_for :category, url: categories_path do |f| %>
     
      <% if @category.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@category.errors.count, "error") %> prohibited
            this category from being saved:
          </h2>
          <ul>
            <% @category.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <table class="table_form">
        <tr>
          <th class="title_new">Tên sản phẩm</th>
          <td><%= f.text_field :name, class: 'name input' %></td>
        </tr><br/>

      </table>
      <p>
        <%= f.button :Tạo  , class: 'btn btn-success'%>
  
        
      </p>
     
    <% end %>
     
    <%= link_to 'Back', categories_path %>

  </div>

app/views/categories/show.html.erb
<section>
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="col-lg-10"><h3 class="panel-title">Danh sach cac san pham :<%= @category.name%><span><%= @count %></span></h3> </div> <div class="col-lg-2"><%= link_to 'Thêm Sản phẩm', new_category_path %></div>
    </div>
    <div class="panel-body">
      <table class="table">
        
          <tr>
            <th>Tên sản phẩm</th>
            <th>Mô tả ngắn</th>
            <th>Chức năng</th>
          </tr>  
        <% @articles.each do |a| %>
          </tr>  
          <td><%= a.title %></td>
          <td><%= a.content %></td>

          <td>
            <%= link_to 'Show', article_path(a) %>
            <%= link_to 'Edit', edit_article_path(a) %>
            <%= link_to 'Destroy', a, method: :delete, data: { confirm: 'Are you sure?' } %>
         </td>
        <% end %>
      </table>

  </div>
</section>